[gcp_service_account]
type = "service_account"
project_id = "lendismart-458818"
private_key_id = "8d439e16833759af161fe26e4272bbcb3858d840"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDJzV7gDuWaJkzC\\n9fzGVAh9XdHlzf8RGaYe5cwT8hqNco6Q+ULwqi21aB1Nc1//S8tU7yLZHeNwaCQB\\nVbZ2BAL+W0Oo3/MZvkcph9OasMYcv4sJnEaVHI9NYOPCch4APX0b0UVtt3HdllgR\\n2bkXSTC8uWodg4l1InMUaD8WOZ6DCqrdm+3SEzMYyxT1L2azvDX2E1CIqjYd4BaN\\n6iAzNVeK9jQ8CpMbsweuKuB1b+I57w1/XCgJkFYXbHtnEaZWTLzL5zYx4HrnIRzc\\nuY7JgTQUChltujf4a77Q+aryHsFmYyK9oyzAWL4W5kS7t1B5GGyxbLFTvzWU81z9\\nneto6+1PAgMBAAECggEAA+T/FIQcMZTVMjA85kWdkFQJTb+4wwBHKat8/DYAd6Bc...\\n-----END PRIVATE KEY-----\\n"
client_email = "lendismart-streamlit@lendismart-458818.iam.gserviceaccount.com"
client_id = "100341403046844039751"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/lendismart-streamlit%40lendismart-458818.iam.gserviceaccount.com"
