[gcp_service_account]
type = "service_account"
project_id = "lendismart-458818"
private_key_id = "7e154f082690960049a818ceb845d6f5af2a5196"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCWr/CZcZf2xqgq
byvvEBwy+Y9weBP1cbPqLwDDR4sChKkvUEmx55xy14tv8pWiRJdqG0MM3Eh+9Q9k
nWmbr6fUN4cevwHFMLQOECRdLXInKIL+GgRKRlu2zxW1U6RluXq+DGYBFRM5Eq+M
NyL4ytmT/yLHGhCxtF0tFJ/PaeV9jPd2OxW6Rr4YJEE1cGIpXCpxnMmMYf+R5GeU
ymrfGvMY1YcDaLTuaUWrKg/Rq0USocs5AeJ0wMHdl0c9QlTKJ6Xog3qrJ1bEKD9v
t2704Hn+/jHMwPeBnOVpcznDhWFn/kIFh3+9a0xSrryMniSOlIH0lw9X/FLzaNPK
2JEyt+UlAgMBAAECggEAGkv38/9D4tgGTul5xE2ObkLpClqaORIvsKWlP28Dzluy
XsRnJ/ngbpY5Cj9OZ7QKrIS3bc4fhLBlkEx8OqQr6LgMB4yT1YLLWUzt26jrq/PA
8HE/4Gpo5P08r5k6LlpxFit5vaSc5y/gnNqeasaTs+Upf4+H7Esqm4xm2z6CwycK
+EbV91LUdxD4pUbG1aVkXETLuW1X1f48BtOAIn9Rk/baBW6dBoF0M4iN4/WAL5Vl
Lo3Cy5RfRtsPquR1cV+XBNzUye0xLgR7Twl7gPH1tRA4d3NiPyMRJj5pc4m++zO+
tgX/iaTlYAwJHs8gFGh5cGqvrZivD7gCADyL+tXN3QKBgQDQake+E7dM9CkOV40O
QgP9A4Fk1My9gcR+LH0nrAjaRIu4vkcbwoLzPQJjC6AmXrK3P0XmZpZjpZW1UEC/
6jv5vi9A2B6SDRsV8XosP3tqy/Qwu7bDZscqcznjxJqcOPvHbfCDcfdBcJgfFKKd
xelI1sdhTnI0j+fF8p0wGfvEnwKBgQC5F4E51Q4umMS/ARZ4tw7kzaLhgAaUbT0I
QCJPOC+1avbgDv5mt2e/+bL68pmnnuzYTWH5BqQR/3U2vIsH87T1XyKQkNjA4f2T
bC407uM4c534NcZGwtDjmnBn+IiKNExeZOXOwJlJyDQuEcvf4W9ZxsJQlHGBKHR1
XOL7Zl2buwKBgQCIeyDSG40syrNcHf9UN+zusm34vtX4v9MSIUYwRZtifALXj1t3
lVA1w10dyU4t8lOsZrX6pHGVfajlHFHam6R87ot5Nk4GrKhxHTo5YbULgdY+V57e
pR6F8QEW4/evmC1hMuCO44Hci8RCjjvTf/g959CXK0zkmNxZp4BCMLHL1wKBgQCB
R4CUM1LvivbI7mqSsFGv0E23MaPm4hHiBGGycW0pSufagb6BYhMOTMsNaouWP3Pw
dMQ8mr3YcFSfgbueN0OqquNKlFFBD9f8s2/muwBr+p1Ys76kyAf9IW7nv/kmhvbc
a57z9SRcG4EOuJFs81nCHAi3HafV7brCCrnjnJE/ZwKBgBt5fIMCn88jhIR8FrNW
Il6IjLqJQRimyI7N3ytfiqNYokf066xM0AsEo6e02b+vn5AkzOpPHJnWkffiMEik
L7FM4GzjK+dQxjyIaqIvCadGW3boC2xLPQGWzUu7PHCrtuqgAoGrx0+6PXd+dz/E
QrCLBIdpAe9f13ffGfBsn5BE
-----END PRIVATE KEY-----
"""
client_email = "lendismart-streamlit@lendismart-458818.iam.gserviceaccount.com"
client_id = "100341403046844039751"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/lendismart-streamlit%40lendismart-458818.iam.gserviceaccount.com"
